name: tingting-app
services:
- name: web
  source_dir: /
  github:
    repo: your-username/your-repo-name
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  build_command: npm run build
  http_port: 3000
  
static_sites:
- name: tingting-static
  source_dir: /
  github:
    repo: your-username/your-repo-name  
    branch: main
  build_command: npm run build
  output_dir: dist
  routes:
  - path: /
    
domains:
- domain: tingting.cz
  type: PRIMARY